spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dietcontroller?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
      maximum-pool-size: 10
      connection-test-query: SELECT 1